#!/usr/bin/env bash

brew update
brew upgrade
brew cleanup
brew doctor

# Install brews
brew install $(cat Brewfile|grep -v "#")

# Install casks
brew cask install $(cat Caskfile|grep -v "#")


# To run dotfile: sh ~/.brew
